---

- name: Install Jenkins software

  hosts: all

  gather_facts: true

  become: yes

  become_method: sudo

  tags: [jenkins]

  tasks:
    - name: Update the software package repository

      yum:

        name: '*'

        state: latest

