---
- name: Install Jenkins software

  hosts: all

  gather_facts: true

  become: yes

  become_method: sudo

  tags: [jenkins]

  tasks:

- import_tasks: install.yml
- import_tasks: configure.yml
...  




# tasks file for JENKINSROLE
